language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "gracemonsters-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the code
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: gracemonsters
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: okr1+Y+WDS7uV5ALjwlPJ5eYoV3ev8ma/9ce9TCna50JNyCQEwtrjVkxgicEzYZFWqBe6DP0Nr7SGPu1Eetr4QwccjdQIwe3mHJ5avgNpmP6tWRvo2WdF1EZ+ZNggoc45blUJer1vS0cXewWMo2jcrkD8Af8+foqqtHduXbgHelnZ2kSYHFlHaxNnFA5o0wsIFk4U5Axt9nr7iUR6mz3Qw//AdBTs7+oUaVHdiwzwHaiqjb/IrcKnSHc+JC1ZiyiuQzu1aaMYUQFEaiSZjXfeKFu3OB7le66gPG3YLpAtAZafbi4TnSZgnBhYpkyZdyxaZkF9K8/G9zN8M2vk5OiGZPNREgoMGg4RXWRamhzeRKGd51vpydkrLwwrLXYDgXNZ2YOCWHegxpYWZYQ/pUa64GbtwiX7RUJD9CjjdwtIz6qzRqyKVsq56O/UPx7a225SqKCwdqV4QVgucy2fUVeGglgQA/92mN/xkWrTLZ+ZjnaDLOGvxRAGidxxb3cVoW79orOZ0SfVESTpVRTFGUNQWt6KsAostH/9SxLeqwK/rHvqvScmtBtonCwD3vpiod8bi6Oxlx351t7lWErcUzH2+/qz5dlMWFKMVDyFNw87r2oybwQTwmXaCnhqaxw1ffxRGH1mSBFeOqwCiqx4jiV/mGpBNBwa0epThPW0+k1eMs=
